apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-infra
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io # Add cascade delete behaviour (deletes both the app and its resources, rather than only the app.)

spec:
  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    # automated:
    #   prune: true
    #   selfHeal: true
      
  source:
    # Should point to your infra repo.
    repoURL: ${GITHUB_REPO}/argo-deploy-applications-infra.git
    targetRevision: main
    path: argo-apps/overlays/local
    plugin:
      name: envsubst
      env:
        - name: ENV
          value: ${ENV}
        - name: DNS_DOMAIN
          value: ${DNS_DOMAIN}
        - name: DNS_ENV
          value: ${DNS_ENV}
        - name: GITHUB_REPO
          value: ${GITHUB_REPO}

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
