apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-experimental
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io # Add cascade delete behaviour (deletes both the app and its resources, rather than only the app.)

spec:
  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    # automated:
    #   prune: true
    #   selfHeal: true

  source:
    # Should point to repo you're going to experiment with
    repoURL: https://github.com/Jojoooo1/argo-deploy-applications-experimental.git
    targetRevision: main
    path: overlays/local/argo-apps
    plugin:
      name: envsubst
      env:
        - name: ENV
          value: local
        - name: DNS_DOMAIN
          value: "cloud-diplomats.com"
        - name: DNS_ENV
          value: '-local'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
