apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-cloud-diplomats
  namespace: argocd

  # Add cascade delete behaviour (deletes both the app and its resources, rather than only the app.)
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    # automated:
    #   prune: true
    #   selfHeal: true
      
  source:
    repoURL: https://github.com/Jojoooo1/argo-deploy-applications.git
    targetRevision: main
    path: argo-apps/overlays/local
    plugin:
      name: envsubst
      env:
        - name: ENV
          value: local
        - name: PROJECT
          value: "sandbox"

        - name: DNS_DOMAIN
          value: "cloud-diplomats.com"
        - name: DNS_ENV
          value: '-local'

  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-diplomats
